
exec-once = waybar & swaync & hypridle &

exec-once = swww-daemon & disown

exec-once = vesktop -startintray
exec-once = Telegram -startintray
exec-once = portmaster -startintray
exec-once = mariadb

exec-once = wl-paste --type text --watch cliphist store


exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

exec-once = hyprctl setcursor macos 24
exec-once = hyprpm reload -n
exec-once = hyprctl reload

exec-once = ~/.local/bin/themes_menu.sh --restore